name: ForsakenCore
version: ${project.version}
main: com.forsakensurvival.forsakencore.ForsakenCore
api-version: 1.16
load: STARTUP
authors: [ Duplexes ]
description: The core plugin for the Forsaken plugin family.
website: ForsakenSurvival.com
commands:
  fly:
  forsakencore:
  gmc:
  gma:
  gms:
  gmsp:
  maintenance:
